SQL> SELECT owner,
	job_name,
	'begin
	sys.dbms_scheduler.set_attribute('''
	|| owner
	|| '.'
	|| job_name
	|| ''',''NLS_ENV'',''NLS_LANGUAGE=''''TURKISH'''' NLS_TERRITORY=''''TURKEY'''' NLS_CURRENCY=''''?'''' 
	NLS_ISO_CURRENCY=''''TURKEY'''' NLS_NUMERIC_CHARACTERS='''',.'''' NLS_CALENDAR=''''GREGORIAN'''' 
	NLS_DATE_FORMAT=''''DD/MM/RRRR'''' NLS_DATE_LANGUAGE=''''TURKISH'''' NLS_SORT=''''TURKISH'''' 
	NLS_TIME_FORMAT=''''HH24:MI:SSXFF'''' NLS_TIMESTAMP_FORMAT=''''DD/MM/RRRR HH24:MI:SSXFF'''' 
	NLS_TIME_TZ_FORMAT=''''HH24:MI:SSXFF TZR'''' NLS_TIMESTAMP_TZ_FORMAT=''''DD/MM/RRRR HH24:MI:SSXFF TZR'''' 
	NLS_DUAL_CURRENCY=''''TL'''' NLS_COMP=''''BINARY'''' NLS_LENGTH_SEMANTICS=''''BYTE'''' 
	NLS_NCHAR_CONV_EXCP=''''FALSE'''''');
	end;'    AS sql_command
	FROM dba_scheduler_jobs
	WHERE owner IN (SELECT username FROM dba_users WHERE oracle_maintained = 'N')
	ORDER BY 1, 2 ;
     
BEGIN 
	sys.DBMS_SCHEDULER.set_attribute ( 
	'HR.JOB_HR_SENDMAIL', 
	'NLS_ENV', 
	'NLS_LANGUAGE=''TURKISH'' NLS_TERRITORY=''TURKEY'' NLS_CURRENCY=''?'' NLS_ISO_CURRENCY=''TURKEY''  
	NLS_NUMERIC_CHARACTERS='',.'' NLS_CALENDAR=''GREGORIAN'' NLS_DATE_FORMAT=''DD/MM/RRRR'' 
	NLS_DATE_LANGUAGE=''TURKISH''  NLS_SORT=''TURKISH'' NLS_TIME_FORMAT=''HH24:MI:SSXFF'' 
	NLS_TIMESTAMP_FORMAT=''DD/MM/RRRR HH24:MI:SSXFF''  NLS_TIME_TZ_FORMAT=''HH24:MI:SSXFF TZR'' 
	NLS_TIMESTAMP_TZ_FORMAT=''DD/MM/RRRR HH24:MI:SSXFF TZR'' NLS_DUAL_CURRENCY=''TL''  
	NLS_COMP=''BINARY'' NLS_LENGTH_SEMANTICS=''BYTE'' NLS_NCHAR_CONV_EXCP=''FALSE'''); 
END; 
